# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

commands:
  activate-service-account:
    steps:
      - run:
          name: Activate GCP service account
          command: |
              GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
              echo ${GCLOUD_SERVICE_KEY} > ${GOOGLE_APPLICATION_CREDENTIALS}
              echo "export GOOGLE_APPLICATION_CREDENTIALS=\"${GOOGLE_APPLICATION_CREDENTIALS}\"" >> $BASH_ENV
              gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}

              gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
              gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

  setup-python-venv:
    description: Set up and create Python venv.
    parameters:
      yogadl:
        type: boolean
        default: false
      extras-requires:
        type: string
        default: ""
      extra-requirements-file:
        type: string
        default: ""
    steps:
      - run: python3 -m venv /tmp/venv
      - run: echo "export PATH=/tmp/venv/bin:\"${PATH}\"" >> $BASH_ENV
      # Useful diagnostics for test failures.
      - run: echo "$PATH"
      - run: /tmp/venv/bin/python3 --version
      - run: which python3
      - run: which pip3
      - run: python3 --version
      - run: pip3 --version
      - run: pip3 install --upgrade pip\<20 wheel setuptools

      # Write dependencies to cachefile to help create the cachekey
      - when:
          condition: <<parameters.yogadl>>
          steps:
            - run: cat setup.py >> /tmp/cachefile
      # Put all the pip requirements into a single /tmp/requirements.txt file.
      - run: echo <<parameters.extras-requires>> > /tmp/requirements.txt
      - run: cat <<parameters.extra-requirements-file>> >> /tmp/requirements.txt
      - run: cat /tmp/requirements.txt >> /tmp/cachefile
      - restore_cache:
          keys:
            - yogadl-python-deps-v1dev4-{{ checksum "/tmp/cachefile" }}
      - when:
          condition: <<parameters.yogadl>>
          steps:
            - run: /tmp/venv/bin/python3 setup.py bdist_wheel -d /tmp
            - run: pip3 install /tmp/yogadl*.whl
            - run: pip3 install --no-deps --force-reinstall /tmp/yogadl*.whl
      - run: pip3 install -r /tmp/requirements.txt
      - save_cache:
          key: yogadl-python-deps-v1dev4-{{ checksum "/tmp/cachefile" }}
          paths:
            - "/tmp/venv"
      # Useful diagnostics for test failures.
      - run: pip3 freeze

jobs:
  lint:
    docker:
      - image: python:3.6.9
    steps:
      - checkout
      - setup-python-venv:
          extra-requirements-file: "requirements.txt"
      - run: make check

  test:
    parameters:
      test-target:
        type: string
      tensorflow-version:
        type: string
        default: "2.1.0"
      gcp:
        type: boolean
        default: false
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - setup-python-venv:
          yogadl: true
          extras-requires: "tensorflow==<<parameters.tensorflow-version>>"
          extra-requirements-file: "requirements.txt"
      - when:
          condition: <<parameters.gcp>>
          steps:
            - gcp-cli/install
            - activate-service-account
      - run: make <<parameters.test-target>>

workflows:
  lint:
    jobs:
      - lint

  test:
    jobs:
      - test:
          context: aws
          matrix:
            parameters:
              test-target: ["test-integration-aws"]
              tensorflow-version: ["1.15.5", "2.4.1"]

      - test:
          context: aws
          matrix:
            parameters:
              test-target: ["test-unit-aws"]

      - test:
          context: gcp
          matrix:
            parameters:
              test-target: ["test-integration-gcp"]
              tensorflow-version: ["1.15.5", "2.4.1"]
              gcp: [true]

      - test:
          context: gcp
          matrix:
            parameters:
              test-target: ["test-unit-gcp"]
              gcp: [true]

      - test:
          matrix:
            parameters:
              test-target: ["test-integration-local"]
              tensorflow-version: ["1.15.5", "2.4.1"]

      - test:
          matrix:
            parameters:
              test-target: ["test-unit-local"]
